### ISSUE TITLE
Segfault on CPU Benchmark map

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1569]
Load CPU Benchmark map from [Benchmark.zip](https://github.com/RigsOfRods/rigs-of-rods/files/2397367/Benchmark.zip):

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00005555559b33b4 in TerrainGeometryManager::getHeightAt (this=0x555556b89520, x=1949.26123, z=1949.26111)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:996
996	      _M_get() const noexcept
(gdb) bt
#0  0x00005555559b33b4 in TerrainGeometryManager::getHeightAt (this=0x555556b89520, x=1949.26123, 
    z=1949.26111) at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:996
#1  0x00005555559b8a49 in TerrainManager::GetHeightAt (this=<optimized out>, x=<optimized out>, 
    z=<optimized out>)
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/terrain/TerrainManager.cpp:636
#2  0x000055555589dc2a in Actor::ResetPosition (this=this@entry=0x555556db6490, px=px@entry=1950.00366, 
    pz=pz@entry=1950.00366, setInitPosition=setInitPosition@entry=true, miny=miny@entry=0)
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/Beam.cpp:1173
#3  0x00005555558b4b05 in RoR::ActorManager::SetupActor(Actor*, std::shared_ptr<RigDef::File>, Ogre::Vector3 const&, Ogre::Quaternion const&, collision_box_t*, bool, bool, int) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/BeamFactory.cpp:297
#4  0x00005555558b50fc in RoR::ActorManager::CreateLocalActor(Ogre::Vector3, Ogre::Quaternion, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, collision_box_t*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const*, RoR::SkinDef*, bool, bool) ()
    at /usr/include/c++/8.2.1/ext/atomicity.h:96
#5  0x00005555559f4477 in GameScript::spawnTruck(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Ogre::Vector3&, Ogre::Vector3&) () at /usr/include/c++/8.2.1/bits/basic_string.h:927
#6  0x00007ffff6fb7638 in X64_CallFunction (args=0x555556b89520, args@entry=0x7fffffffc800, cnt=365, 
    func=0x555556be8958, 
    func@entry=0x5555559f4320 <GameScript::spawnTruck(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Ogre::Vector3&, Ogre::Vector3&)>, retQW2=@0x555556be88e0: 4477658893642874910, 
    returnFloat=205)
    at /home/babis/Downloads/ror-dependencies-1.8/Source/angelscript/source/as_callfunc_x64_gcc.cpp:74
#7  0x00007ffff6fb7948 in CallSystemFunctionNative (context=context@entry=0x55555685bc10, descr=descr@entry=
    0x55555655f540, obj=0x555556560c30, args=<optimized out>, retPointer=<optimized out>, 
    retQW2=@0x7fffffffca50: 0, secondObject=0x0)
    at /home/babis/Downloads/ror-dependencies-1.8/Source/angelscript/source/as_callfunc_x64_gcc.cpp:468
#8  0x00007ffff6fb6818 in CallSystemFunction(int, asCContext*) ()
    at /home/babis/Downloads/ror-dependencies-1.8/Source/angelscript/source/as_callfunc.cpp:718
#9  0x00007ffff6fed02f in asCContext::ExecuteNext (this=this@entry=0x55555685bc10)
    at /home/babis/Downloads/ror-dependencies-1.8/Source/angelscript/source/as_context.cpp:2525
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff6feefc8 in asCContext::Execute() ()
    at /home/babis/Downloads/ror-dependencies-1.8/Source/angelscript/source/as_context.cpp:1318
#11 0x0000555555a0a89c in ScriptEngine::loadScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/scripting/ScriptEngine.cpp:815
#12 0x00005555559b9821 in TerrainManager::initScripting() ()
    at /usr/include/c++/8.2.1/bits/basic_string.h:927
#13 0x00005555559babcc in TerrainManager::initSubSystems() ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/terrain/TerrainManager.cpp:204
#14 0x00005555559bbe0a in TerrainManager::LoadAndPrepareTerrain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/terrain/TerrainManager.cpp:151
#15 0x00005555556f76a9 in SimController::LoadTerrain() () at /usr/include/c++/8.2.1/bits/basic_string.h:927
#16 0x00005555556f823a in SimController::SetupGameplayLoop() ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:1967
#17 0x00005555556b7489 in main ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/main.cpp:341
#18 0x00007ffff69de223 in __libc_start_main () from /usr/lib/libc.so.6
#19 0x00005555556ccfce in _start () at /usr/include/c++/8.2.1/bits/char_traits.h:285
```
GPU Benchmark works

From #dev channel:

> Another🦊GuyLast Saturday at 2:09 PM
@ulteq I think the issue is that angelscript is loaded here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/TerrainManager.cpp#L170
But the terrain is loaded here: https://github.com/RigsOfRods/rigs-of-rods/blob/master/source/main/terrain/TerrainManager.cpp#L178
So angelscript will try and get the height of a terrain that hasn't loaded yet
But for some reason it doesn't crash on windows

**Comment by tritonas00** [comment]
Almost same situation with simple test terrain 12 cars:
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00005555559da920 in TerrainGeometryManager::getMaxTerrainSize (this=0x5555572351b0)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:996
996	      _M_get() const noexcept
(gdb) bt
#0  0x00005555559da920 in TerrainGeometryManager::getMaxTerrainSize (this=0x5555572351b0)
    at /usr/include/c++/8.2.1/bits/shared_ptr_base.h:996
#1  0x00005555559e76f4 in TerrainObjectManager::LoadTObjFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainManager.h:44
#2  0x00005555559dff4e in TerrainManager::loadTerrainObjects() ()
    at /usr/include/c++/8.2.1/bits/basic_string.h:927
#3  0x00005555559e1659 in TerrainManager::loadTerrain(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainManager.cpp:185
#4  0x0000555555727519 in SimController::LoadTerrain() () at /usr/include/c++/8.2.1/bits/basic_string.h:927
#5  0x00005555557281a6 in SimController::SetupGameplayLoop() ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2194
#6  0x00005555556e3294 in main ()
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:370
#7  0x00007ffff6c99223 in __libc_start_main () from /usr/lib/libc.so.6
#8  0x00005555556fc09e in _start () at /usr/include/c++/8.2.1/bits/char_traits.h:285
```

**Comment by tritonas00** [comment]
fixed on https://github.com/RigsOfRods/rigs-of-rods/pull/1640
