### ISSUE TITLE
Segfault when loading volvo-fmx-effer

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1577]
Load http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/0f86053526958080c5313f88d092bdc377f7fddb_volvo-fmx-effer-1355.zip
```
Thread 6 "RoR" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdeef8700 (LWP 22642)]
0x00005555558a7da2 in Actor::calcShocks2(int, float, float&, float&, bool) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/Beam.cpp:2531
2531	                        if (ar_beams[scount].shock && (ar_beams[scount].shock->flags & SHOCK_FLAG_ISTRIGGER)) // don't mess anything up if the user set the number too big
```
```
(gdb) bt
#0  0x00005555558a7da2 in Actor::calcShocks2(int, float, float&, float&, bool) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/Beam.cpp:2531
#1  0x00005555558bd211 in Actor::calcBeams(bool) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/BeamForcesEuler.cpp:1335
#2  0x00005555558beb42 in Actor::calcForcesEulerCompute(int, int) ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/BeamForcesEuler.cpp:69
#3  0x00005555558aea51 in RoR::ActorManager::<lambda()>::operator() (__closure=0x7fffc8000b70)
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/BeamFactory.cpp:1208
#4  std::_Function_handler<void(), RoR::ActorManager::UpdatePhysicsSimulation()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/8.2.1/bits/std_function.h:297
#5  0x00005555558b32e4 in std::function<void ()>::operator()() const (this=0x7fffc8000b40)
    at /usr/include/c++/8.2.1/bits/std_function.h:682
#6  ThreadPool::Parallelize(std::vector<std::function<void ()>, std::allocator<std::function<void ()> > > const&) (task_funcs=std::vector of length 1, capacity 1 = {...}, this=0x5555566b2350)
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/threadpool/ThreadPool.h:186
#7  RoR::ActorManager::UpdatePhysicsSimulation() ()
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/physics/BeamFactory.cpp:1226
#8  0x00005555558b86e4 in std::function<void ()>::operator()() const (this=0x555557d59390)
    at /usr/include/c++/8.2.1/bits/std_function.h:682
#9  ThreadPool::ThreadPool(int)::{lambda()#1}::operator()() const (__closure=0x55555669a048)
    at /home/babis/Downloads/ror-dependencies-1.8/rigs-of-rods/source/main/threadpool/ThreadPool.h:135
#10 std::__invoke_impl<void, ThreadPool::ThreadPool(int)::{lambda()#1}>(std::__invoke_other, ThreadPool::ThreadPool(int)::{lambda()#1}&&) (__f=...) at /usr/include/c++/8.2.1/bits/invoke.h:60
#11 std::__invoke<ThreadPool::ThreadPool(int)::{lambda()#1}>(std::__invoke_result&&, (ThreadPool::ThreadPool(int)::{lambda()#1}&&)...) (__fn=...) at /usr/include/c++/8.2.1/bits/invoke.h:95
#12 std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555669a048) at /usr/include/c++/8.2.1/thread:244
#13 std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> >::operator()() (
    this=0x55555669a048) at /usr/include/c++/8.2.1/thread:253
#14 std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> > >::_M_run() (this=0x55555669a040) at /usr/include/c++/8.2.1/thread:196
#15 0x00007ffff6dd9063 in execute_native_thread_routine ()
---Type <return> to continue, or q <return> to quit---
    at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#16 0x00007ffff7316a9d in start_thread () from /usr/lib/libpthread.so.0
#17 0x00007ffff6ab5a43 in clone () from /usr/lib/libc.so.6
```

**Comment by only-a-ptr** [comment]
Curious, it crashes in physics code. That means the spawner had let through a faulty vehicle.
