### ISSUE TITLE
nhelens texture issue

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1939]
Have [North St Helens](http://www.austingratzer.com/rigs/downloads.php?do=file&id=98&act=down&actionhash=guest) and [North St Helens Modded](http://www.austingratzer.com/rigs/downloads.php?do=file&id=358&act=down&actionhash=guest) in packs and load one of them:

![nh](https://user-images.githubusercontent.com/2660424/50290085-4791d300-0473-11e9-83e1-9c874e292346.png)

The issue doesn't occur if you have one **or** another

**Comment by tritonas00** [comment]
Also North St Helens Modded segfaults:

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="a1da0UID-nhelens.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
260	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="a1da0UID-nhelens.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
#1  0x00007ffff7176c70 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str="a1da0UID-nhelens.os", 
    this=<optimized out>) at /usr/include/c++/8.2.1/bits/basic_string.h:1364
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str="a1da0UID-nhelens.os", this=<optimized out>)
    at /usr/include/c++/8.2.1/bits/basic_string.h:695
#3  Ogre::Resource::_notifyOrigin (origin="a1da0UID-nhelens.os", this=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/OGRE/OgreResource.h:412
#4  Caelum::CaelumSystemScriptTranslator::translate (this=0x555555c47ec0, compiler=0x555555c0f8c0, node=...)
    at /home/babis/Downloads/ror-dependencies/Source/caelum/main/src/CaelumScriptTranslator.cpp:414
#5  0x00007ffff7795652 in Ogre::ScriptCompiler::compile (this=0x555555c0f8c0, nodes=..., group=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:358
#6  0x00007ffff7795a13 in Ogre::ScriptCompilerManager::parseScript (this=0x555555c0f880, stream=..., groupName="General-Reloaded-2")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:1654
#7  0x00007ffff775eb3c in Ogre::ResourceGroupManager::parseResourceGroupScripts (this=0x555555c08fd0, grp=0x555558ea79c0)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:1018
#8  0x00007ffff775ef1a in Ogre::ResourceGroupManager::initialiseResourceGroup (this=0x555555c08fd0, name="General-Reloaded-2")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:119
#9  0x000055555587a59f in CacheSystem::checkResourceLoaded (this=0x555555b7c790 <RoR::App::g_content_manager+16>, t=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1321
#10 0x000055555587a785 in CacheSystem::checkResourceLoaded (this=0x555555b7c790 <RoR::App::g_content_manager+16>, 
    filename="a1da0UID-monorail.truck", group="") at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1294
#11 0x000055555591f568 in TerrainObjectManager::LoadTObjFile (this=this@entry=0x555557fe7180, odefname="a1da0UID-nhelens.tobj")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainObjectManager.cpp:508
#12 0x0000555555913bee in TerrainManager::loadTerrainObjects (this=0x555557fd5a10) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#13 0x0000555555915511 in TerrainManager::LoadAndPrepareTerrain (this=this@entry=0x555557fd5a10, filename="a1da0UID-nhelensModded.terrn2")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainManager.cpp:210
#14 0x0000555555652bb6 in SimController::LoadTerrain (this=0x7fffffffe470) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#15 0x0000555555654029 in SimController::SetupGameplayLoop (this=this@entry=0x7fffffffe470)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2039
#16 0x0000555555609ce5 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:334
```

Leaving it alone (without North St Helens) makes it work again

**Comment by tritonas00** [comment]
I can't reproduce it anymore.
