### ISSUE TITLE
Some maps segfault when they coexist with others

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#1945]
[North St Helens](http://www.austingratzer.com/rigs/downloads.php?do=file&id=98&act=down&actionhash=guest) and [North St Helens Modded](http://www.austingratzer.com/rigs/downloads.php?do=file&id=358&act=down&actionhash=guest):

Load North St Helens Modded:

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="a1da0UID-nhelens.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
260	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="a1da0UID-nhelens.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
#1  0x00007ffff7176c70 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str="a1da0UID-nhelens.os", 
    this=<optimized out>) at /usr/include/c++/8.2.1/bits/basic_string.h:1364
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str="a1da0UID-nhelens.os", this=<optimized out>)
    at /usr/include/c++/8.2.1/bits/basic_string.h:695
#3  Ogre::Resource::_notifyOrigin (origin="a1da0UID-nhelens.os", this=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/OGRE/OgreResource.h:412
#4  Caelum::CaelumSystemScriptTranslator::translate (this=0x555555c47ec0, compiler=0x555555c0f8c0, node=...)
    at /home/babis/Downloads/ror-dependencies/Source/caelum/main/src/CaelumScriptTranslator.cpp:414
#5  0x00007ffff7795652 in Ogre::ScriptCompiler::compile (this=0x555555c0f8c0, nodes=..., group=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:358
#6  0x00007ffff7795a13 in Ogre::ScriptCompilerManager::parseScript (this=0x555555c0f880, stream=..., groupName="General-Reloaded-2")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:1654
#7  0x00007ffff775eb3c in Ogre::ResourceGroupManager::parseResourceGroupScripts (this=0x555555c08fd0, grp=0x555558ea79c0)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:1018
#8  0x00007ffff775ef1a in Ogre::ResourceGroupManager::initialiseResourceGroup (this=0x555555c08fd0, name="General-Reloaded-2")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:119
#9  0x000055555587a59f in CacheSystem::checkResourceLoaded (this=0x555555b7c790 <RoR::App::g_content_manager+16>, t=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1321
#10 0x000055555587a785 in CacheSystem::checkResourceLoaded (this=0x555555b7c790 <RoR::App::g_content_manager+16>, 
    filename="a1da0UID-monorail.truck", group="") at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1294
#11 0x000055555591f568 in TerrainObjectManager::LoadTObjFile (this=this@entry=0x555557fe7180, odefname="a1da0UID-nhelens.tobj")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainObjectManager.cpp:508
#12 0x0000555555913bee in TerrainManager::loadTerrainObjects (this=0x555557fd5a10) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#13 0x0000555555915511 in TerrainManager::LoadAndPrepareTerrain (this=this@entry=0x555557fd5a10, filename="a1da0UID-nhelensModded.terrn2")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/terrain/TerrainManager.cpp:210
#14 0x0000555555652bb6 in SimController::LoadTerrain (this=0x7fffffffe470) at /usr/include/c++/8.2.1/bits/basic_string.h:936
#15 0x0000555555654029 in SimController::SetupGameplayLoop (this=this@entry=0x7fffffffe470)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2039
#16 0x0000555555609ce5 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:334
```

Same situation with Ship_Yard_by_DirtGamer301 and simple2-terrain:

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="simple.terrn.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
260	/build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc: No such file or directory.
(gdb) bt
#0  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign (this=0x90, __str="simple.terrn.os")
    at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:260
#1  0x00007ffff7176c70 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign (__str="simple.terrn.os", 
    this=<optimized out>) at /usr/include/c++/8.2.1/bits/basic_string.h:1364
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator= (__str="simple.terrn.os", this=<optimized out>)
    at /usr/include/c++/8.2.1/bits/basic_string.h:695
#3  Ogre::Resource::_notifyOrigin (origin="simple.terrn.os", this=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/Dependencies_Linux/include/OGRE/OgreResource.h:412
#4  Caelum::CaelumSystemScriptTranslator::translate (this=0x555555c47ec0, compiler=0x555555c0f8c0, node=...)
    at /home/babis/Downloads/ror-dependencies/Source/caelum/main/src/CaelumScriptTranslator.cpp:414
#5  0x00007ffff7795652 in Ogre::ScriptCompiler::compile (this=0x555555c0f8c0, nodes=..., group=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:358
#6  0x00007ffff7795a13 in Ogre::ScriptCompilerManager::parseScript (this=0x555555c0f880, stream=..., groupName="General-24")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreScriptCompiler.cpp:1654
#7  0x00007ffff775eb3c in Ogre::ResourceGroupManager::parseResourceGroupScripts (this=0x555555c08fd0, grp=0x55555751fbc0)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:1018
#8  0x00007ffff775ef1a in Ogre::ResourceGroupManager::initialiseResourceGroup (this=this@entry=0x555555c08fd0, name="General-24")
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreResourceGroupManager.cpp:119
#9  0x00005555558774b4 in CacheSystem::loadSingleZipInternal (this=0x555555b7c790 <RoR::App::g_content_manager+16>, zippath=..., 
    cfactor=<optimized out>) at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1398
#10 0x0000555555877989 in CacheSystem::loadSingleZip (this=0x555555b7c790 <RoR::App::g_content_manager+16>, f=...)
    at /usr/include/c++/8.2.1/bits/basic_string.h:936
#11 0x000055555587843b in CacheSystem::checkForNewZipsInResourceGroup (this=0x555555b7c790 <RoR::App::g_content_manager+16>, 
    resource_bundles=std::set with 325 elements = {...}, group="Packs")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:1498
#12 0x00005555558787c8 in CacheSystem::checkForNewContent (this=0x555555b7c790 <RoR::App::g_content_manager+16>)
    at /usr/include/c++/8.2.1/ext/new_allocator.h:79
#13 0x0000555555879542 in CacheSystem::incrementalCacheUpdate (this=0x555555b7c790 <RoR::App::g_content_manager+16>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:459
#14 0x000055555587c6ac in CacheSystem::LoadModCache (this=this@entry=0x555555b7c790 <RoR::App::g_content_manager+16>, validity=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/CacheSystem.cpp:142
#15 0x00005555558968f2 in RoR::ContentManager::InitModCache (this=0x555555b7c780 <RoR::App::g_content_manager>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/resources/ContentManager.cpp:284
#16 0x0000555555609bf8 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:256
```

**Comment by AnotherFoxGuy** [comment]
This crash occurs if there are two Caelum .os scripts with the same name

**Comment by ulteq** [comment]
Yes, but it shouldn't crash on that. And it didn't with Ogre 1.9.

**Comment by AnotherFoxGuy** [comment]
This crash occurred after #1608

**Comment by ulteq** [comment]
> This crash occurred after #1608

@only-a-ptr Would be great if you could look into it one day.
