### ISSUE TITLE
manitou-MRT-1850 segfaults with skidmarks enabled

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2037]
[manitou-MRT-1850](https://www63.zippyshare.com/v/T7S6daGf/file.html)

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x0000555555801e17 in Actor::updateSkidmarks (this=this@entry=0x55555afc2ab0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Beam.cpp:2718
2718
```
```
#0  0x0000555555801e17 in Actor::updateSkidmarks (this=this@entry=0x55555afc2ab0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Beam.cpp:2718
#1  0x000055555581416d in RoR::ActorManager::UpdateActors (this=this@entry=0x7fffffffe4b8, player_actor=0x55555afc2ab0, dt=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/BeamFactory.cpp:987
#2  0x000055555565eec9 in SimController::UpdateSimulation (this=0x7fffffffe490, dt=0.00518847862)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:1738
#3  0x000055555565fad3 in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffe490)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2142
#4  0x000055555560a9a2 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:337
```
Disabling skidmarks in settings fixes the issue

**Comment by ulteq** [comment]
> Disabling skidmarks in settings fixes the issue

It reduces the chance that something goes wrong. But the underlying issue seems to be some kind of memory corruption.

**Comment by only-a-ptr** [comment]
@tritonas00 Your download is dead, is it this vehicle? http://archives.rigsofrods.net/repo/files/repofiles-1st-batch/9d02800e5d325a3340cd97b0bf0622ea59bbd60e_Manitou-MRT-Telehandler.zip

**Comment by tritonas00** [comment]
@only-a-ptr https://www93.zippyshare.com/v/RBnsXPne/file.html

**Comment by only-a-ptr** [comment]
@tritonas00 I can't reproduce it (Win10, OpenGL, x64 build). Tell me more: what map you use, how you drive, when exactly it crashes...

**Comment by tritonas00** [comment]
hmm you are right, i cant reproduce it anymore either
@ulteq can you reproduce with latest master?

**Comment by ulteq** [comment]
No :confused:

**Comment by tritonas00** [comment]
:fearful:

**Comment by only-a-ptr** [comment]
😆
