### ISSUE TITLE
Multiplayer: Various client segfaults

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#2178]
- [x] 1.
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
RoR::GfxActor::CalculateDriverPos (this=0x555564f02520, out_pos=..., out_rot=...) at ~/source/main/gfx/GfxActor.cpp:2091
2091        const Ogre::Vector3 x_pos = nodes[driverseat_prop->nodex].AbsPosition;
(gdb) bt
#0  RoR::GfxActor::CalculateDriverPos (this=0x555564f02520, out_pos=..., out_rot=...) at ~/source/main/gfx/GfxActor.cpp:2091
#1  0x0000555555644584 in RoR::GfxCharacter::UpdateCharacterInScene (this=0x555564f5bbd0) at ~/source/main/physics/Beam.h:172
#2  0x000055555566c968 in RoR::GfxScene::UpdateScene (this=this@entry=0x7fffffffe050, dt_sec=dt_sec@entry=0.0166722331) at ~/source/main/gfx/DustManager.cpp:205
#3  0x0000555555660b52 in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffdf20) at ~/source/main/gameplay/RoRFrameListener.cpp:2243
```
- [ ] 2.
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x000055555567cc17 in RoR::GfxActor::UpdateWheelVisuals (this=this@entry=0x5555575b6a50)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/GfxActor.cpp:1909
1909            if (w.wx_flex_mesh != nullptr && w.wx_flex_mesh->flexitPrepare())

```
- [x] 3.
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x0000000000000111 in ?? ()
(gdb) bt
#0  0x0000000000000111 in ?? ()
#1  0x0000555555642275 in RoR::GfxCharacter::~GfxCharacter (this=0x555559ffc2e0, __in_chrg=<optimized out>) at /usr/include/c++/8.2.1/bits/unique_ptr.h:342
#2  0x000055555564241a in Character::~Character (this=0x555562cca660, __in_chrg=<optimized out>) at ~/source/main/gameplay/Character.cpp:78
#3  0x000055555562a6e9 in std::default_delete<Character>::operator() (this=0x55556024dab0, __ptr=0x555562cca660) at /usr/include/c++/8.2.1/bits/unique_ptr.h:347
#4  std::unique_ptr<Character, std::default_delete<Character> >::~unique_ptr (this=0x55556024dab0, __in_chrg=<optimized out>) at /usr/include/c++/8.2.1/bits/unique_ptr.h:274
#5  std::_Destroy<std::unique_ptr<Character, std::default_delete<Character> > > (__pointer=0x55556024dab0) at /usr/include/c++/8.2.1/bits/stl_construct.h:98
#6  std::_Destroy_aux<false>::__destroy<std::unique_ptr<Character, std::default_delete<Character> >*> (__last=<optimized out>, __first=0x55556024dab0) at /usr/include/c++/8.2.1/bits/stl_construct.h:108
#7  std::_Destroy<std::unique_ptr<Character, std::default_delete<Character> >*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/8.2.1/bits/stl_construct.h:137
#8  std::_Destroy<std::unique_ptr<Character, std::default_delete<Character> >*, std::unique_ptr<Character, std::default_delete<Character> > > (__last=0x55556024dac0, __first=<optimized out>) at /usr/include/c++/8.2.1/bits/stl_construct.h:206
#9  std::vector<std::unique_ptr<Character, std::default_delete<Character> >, std::allocator<std::unique_ptr<Character, std::default_delete<Character> > > >::~vector (this=0x7fffffffe038, __in_chrg=<optimized out>)
    at /usr/include/c++/8.2.1/bits/stl_vector.h:567
#10 RoR::CharacterFactory::~CharacterFactory (this=0x7fffffffe038, __in_chrg=<optimized out>) at ~/source/main/gameplay/CharacterFactory.h:31
#11 SimController::~SimController (this=0x7fffffffdf20, __in_chrg=<optimized out>) at ~/source/main/gameplay/RoRFrameListener.h:61
```
- [x] 4.
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
RoR::ActorManager::CheckNetworkStreamsOk (this=0x28, sourceid=72) at ~/rigs-of-rods/source/main/physics/BeamFactory.cpp:509
509        if (m_stream_mismatches[sourceid].size() > 0)
(gdb) bt
#0  RoR::ActorManager::CheckNetworkStreamsOk (this=0x28, sourceid=72) at ~/rigs-of-rods/source/main/physics/BeamFactory.cpp:509
#1  0x00005555557df7aa in RoR::GUI::MpClientList::updateSlot (this=<optimized out>, row=0x5555581987f8, c=..., self=<optimized out>) at ~/rigs-of-rods/source/main/gameplay/RoRFrameListener.h:100
#2  0x00005555557e07dd in RoR::GUI::MpClientList::update (this=0x5555581987a0) at ~/rigs-of-rods/source/main/gui/panels/GUI_MultiplayerClientList.cpp:322
#3  0x000055555562d898 in RoR::MainMenu::MainMenuLoopUpdate (this=0x7fffffffdd00, seconds_since_last_frame=0.0166713931) at ~/rigs-of-rods/source/main/MainMenu.cpp:149
#4  0x000055555562dccc in RoR::MainMenu::EnterMainMenuLoop (this=this@entry=0x7fffffffdd00) at ~/rigs-of-rods/source/main/MainMenu.cpp:84
#5  0x0000555555609516 in main (argc=<optimized out>, argv=<optimized out>) at ~/rigs-of-rods/source/main/main.cpp:333
```

**Comment by tritonas00** [comment]
```
Thread 17 "RoR" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd4aa4700 (LWP 32322)]
FlexBody::ComputeFlexbody (this=0x55555fac0e20) at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexBody.cpp:632
632            Vector3 diffX = nodes[m_locators[i].nx].AbsPosition - nodes[m_locators[i].ref].AbsPosition;
```
```
#0  FlexBody::ComputeFlexbody (this=0x55555fac0e20) at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexBody.cpp:632
#1  0x000055555581eeb1 in std::function<void ()>::operator()() const (this=0x55555cddd8e0) at /usr/include/c++/8.2.1/bits/std_function.h:682
#2  ThreadPool::ThreadPool(int)::{lambda()#1}::operator()() const (__closure=0x55555789c318)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/threadpool/ThreadPool.h:135
#3  std::__invoke_impl<void, ThreadPool::ThreadPool(int)::{lambda()#1}>(std::__invoke_other, ThreadPool::ThreadPool(int)::{lambda()#1}&&) (__f=...)
    at /usr/include/c++/8.2.1/bits/invoke.h:60
#4  std::__invoke<ThreadPool::ThreadPool(int)::{lambda()#1}>(std::__invoke_result&&, (ThreadPool::ThreadPool(int)::{lambda()#1}&&)...) (__fn=...)
    at /usr/include/c++/8.2.1/bits/invoke.h:95
#5  std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x55555789c318)
    at /usr/include/c++/8.2.1/thread:244
#6  std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> >::operator()() (this=0x55555789c318)
    at /usr/include/c++/8.2.1/thread:253
#7  std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(int)::{lambda()#1}> > >::_M_run() (this=0x55555789c310)
    at /usr/include/c++/8.2.1/thread:196
#8  0x00007ffff705b063 in std::execute_native_thread_routine (__p=0x55555789c310) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#9  0x00007ffff7954a9d in start_thread () from /usr/lib/libpthread.so.0
```

**Comment by ulteq** [comment]
I can't reproduce any of them anymore.
