### ISSUE TITLE
Game crash after hooking to a trailer.

### ISSUE THREAD

**Issue by AgentV12** [RigsOfRods/rigs-of-rods#2378]
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/3293488/RoR.log)
This was on the latest development build.
I was using the F-250 XLT on Hillside Reversed, and spawned a 44 ft tilt deck goose-neck trailer. I spent 5 minutes trying to load an international 1055 onto it, realized it was too narrow, and deleted the tilt deck, while it was still attached to the F-250. I then spawned the Felling tag trailer, but when I tried to hook it to the F-250, the game crashed.

I had this happen before on the dev builds. I deleted the Eager Beaver stinger while it was attached to it, and connected to the eager beaver tag axle, which caused the game to crash.

**Links to the mods used:**
http://archives.rigsofrods.net/repo/files/repofiles-4th-batch/N-MassTractors_1.zip
https://forum.rigsofrods.org/resources/felling-tag-trailer.102/
https://forum.rigsofrods.org/resources/44ft-tilt-deck-gooseneck-trailer.5/
https://forum.rigsofrods.org/resources/hillside.541/
https://forum.rigsofrods.org/resources/2014-ford-f-250-super-duty-xlt.97/

**Comment by tritonas00** [comment]
Strange, i can't reproduce it. 

Spawned F-250 XLT, spawned 44 ft tilt deck goose-neck trailer, attached it to the F-250, deleted it, spawned the Felling, attached it to the F-250, all good

**Comment by tritonas00** [comment]
reproduced

lock mv4s on w900 rollback, remove mv4s, spawn new mv4s and lock it again:
the lock icon is already on from the previous lock and removing the vehicle crashes the game

```
free(): invalid pointer

Thread 1 "RoR" received signal SIGABRT, Aborted.
0x00007ffff6c13755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6c13755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff6bfe851 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff6c55a38 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff6c5c25a in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff6c5d9cc in _int_free () from /usr/lib/libc.so.6
#5  0x00007ffff75fb8d0 in Ogre::BillboardSet::~BillboardSet (this=0x55555f168970, __in_chrg=<optimized out>)
    at /usr/include/c++/9.1.0/bits/stl_iterator.h:819
#6  0x00007ffff75fbc09 in Ogre::BillboardSet::~BillboardSet (this=0x55555f168970, __in_chrg=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreBillboardSet.cpp:102
#7  0x00007ffff777db0e in Ogre::SceneManager::destroyMovableObject (typeName=..., name=..., this=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreSceneManager.cpp:4154
#8  Ogre::SceneManager::destroyMovableObject (this=<optimized out>, name=..., typeName=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/src/OgreSceneManager.cpp:4136
#9  0x00007ffff777dc02 in Ogre::SceneManager::destroyMovableObject (this=0x5555561db4b0, m=0x55555f168970)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/OgreMain/include/OgreMovableObject.h:202
#10 0x0000555555830b6b in Actor::~Actor (this=0x55555f1ca0b0, __in_chrg=<optimized out>) at /usr/include/c++/9.1.0/bits/stl_vector.h:1040
#11 0x0000555555831582 in Actor::~Actor (this=0x55555f1ca0b0, __in_chrg=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Beam.cpp:76
#12 0x0000555555839bc4 in RoR::ActorManager::DeleteActorInternal (this=0x7fffffffe428, actor=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/BeamFactory.cpp:919
#13 0x000055555565fec6 in SimController::UpdateSimulation (this=0x7fffffffe400, dt=0.0166667663)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:1599
#14 0x0000555555661c2b in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffe400)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2271
#15 0x0000555555603431 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:354
```

probably something in not properly cleaned up
