### ISSUE TITLE
Crash with XBOX360 controller connected (Linux)

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/rigs-of-rods#24]
Happens when entering a vehicle.

RoR console output:

```
LinuxForceFeedback(19) : Setting master gain to 1 => 65535
Texture: mv4speedo.dds: Loading 1 faces(PF_DXT1,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_DXT1,256x256x1.
Texture: mv4tacho.dds: Loading 1 faces(PF_R8G8B8,256x256x1) with 8 custom mipmaps from Image. Internal format is PF_X8R8G8B8,256x256x1.
Texture: tractioncontrol-2.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) with 0 generated mipmaps from Image. Internal format is PF_A8R8G8B8,64x64x1.
Texture: antilockbrake-2.png: Loading 1 faces(PF_A8R8G8B8,64x64x1) with 0 generated mipmaps from Image. Internal format is PF_A8R8G8B8,64x64x1.
terminate called after throwing an instance of 'OIS::Exception'
  what():  Unknown error creating effect (may be the device is full)->..
Aborted (core dumped)
```

gdb:

```
Core was generated by `./RoR'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f4832552bb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f4832552bb9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f4832555fc8 in __GI_abort () at abort.c:89
#2  0x00007f4832e5e6b5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f4832e5c836 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f4832e5c863 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f4832e5caa2 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f48342e1975 in OIS::LinuxForceFeedback::_upload(ff_effect*, OIS::Effect const*) () from /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so
#7  0x00007f48342e2002 in OIS::LinuxForceFeedback::_updateConstantEffect(OIS::Effect const*) () from /usr/lib/x86_64-linux-gnu/libOIS-1.3.0.so
#8  0x00000000006d1190 in ForceFeedback::setForces(float, float, float, float, float) ()
#9  0x00000000005284ec in RoRFrameListener::frameStarted(Ogre::FrameEvent const&) ()
#10 0x00007f4834f4bf2c in Ogre::Root::_fireFrameStarted(Ogre::FrameEvent&) () from /usr/local/lib/libOgreMain.so.1.8.1
#11 0x00007f4834f4d7d1 in Ogre::Root::_fireFrameStarted() () from /usr/local/lib/libOgreMain.so.1.8.1
#12 0x00007f4834f4d8d9 in Ogre::Root::renderOneFrame() () from /usr/local/lib/libOgreMain.so.1.8.1
#13 0x00000000007a3704 in RoR::MainThread::EnterGameplayLoop() ()
#14 0x00000000007a88a0 in RoR::MainThread::Go() ()
#15 0x00000000004fee7e in main ()
```

**Comment by Hiradur** [comment]
It's because the force feedback is broken under Linux. I temporarily disabled it on Linux for now.

**Comment by skybon** [comment]
@Hiradur does it occur with both drivers (xpad and xboxdrv)?

**Comment by Hiradur** [comment]
Only tried xboxdrv

**Comment by CuriousMike56** [comment]
Is this still valid? @tritonas00 do you have an Xbox controller to test?

**Comment by tritonas00** [comment]
nope

**Comment by only-a-ptr** [comment]
Let's close this; Xbox controller + Linux + Forcefeedback is not a frequent combo, and porting to SDL input will obsolete this anyway.
