### ISSUE TITLE
Reload current vehicle segfault

### ISSUE THREAD

**Issue by tritonas00** [RigsOfRods/rigs-of-rods#2424]
Load a container (like 20ft) or anything without dash, activate it and press `Reload current vehicle`

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
RoR::Renderdash::setEnable (this=0x200041300000000, en=true)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/Renderdash.cpp:74
74	    m_rtt_tex->setActive(en);
(gdb) bt
#0  RoR::Renderdash::setEnable (this=0x200041300000000, en=true)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/Renderdash.cpp:74
#1  0x0000555555672195 in RoR::GfxActor::SetRenderdashActive (this=<optimized out>, active=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/GfxActor.cpp:2439
#2  0x0000555555650ef2 in SimController::ChangePlayerActor (this=0x7fffffffe430, actor=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/Beam.h:161
#3  0x0000555555660626 in SimController::UpdateSimulation (this=0x7fffffffe430, dt=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:1724
#4  0x0000555555661a9b in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffe430)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2257
#5  0x00005555556033a1 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:354
```

**Comment by only-a-ptr** [comment]
Thanks! It's not related to dash, though, it affects everything - it's just coincidence that it won't crash with dash.
