### ISSUE TITLE
RoR crashing when turning on extra plane engines

### ISSUE THREAD

**Issue by 4x4convoy** [RigsOfRods/rigs-of-rods#2431]
Using the latest dev build if you try and turn on more engines than the plane has the game will crash with no error message. It will do this with every plane that uses less than 4 engines, i just used the 767. Here is a video and the mod used in the example video.
[https://forum.rigsofrods.org/resources/boeing-767.96/](url)
[https://streamable.com/4v0gn](url)

**Comment by tritonas00** [comment]
indeed

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x0000555555737711 in OverlayWrapper::mouseMoved (_arg=..., this=0x55555d05fb60)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/OverlayWrapper.cpp:658
658	                    player_actor->ar_autopilot->adjIAS(-1);
(gdb) bt
#0  0x0000555555737711 in OverlayWrapper::mouseMoved (_arg=..., this=0x55555d05fb60)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/OverlayWrapper.cpp:658
#1  OverlayWrapper::mouseMoved (this=0x55555d05fb60, _arg=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/OverlayWrapper.cpp:528
#2  0x000055555573079e in GUIInputManager::mousePressed (this=<optimized out>, _arg=..., _id=OIS::MB_Left)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIInputManager.cpp:208
#3  0x00005555559bb95b in InputEngine::mousePressed (this=0x555557545010, arg=..., id=OIS::MB_Left)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/InputEngine.cpp:2287
#4  0x00007ffff7b42237 in OIS::LinuxMouse::_processXEvents() () from /home/babis/Downloads/ror-dependencies/Dependencies_Linux/lib/libOIS.so
#5  0x00007ffff7b426e2 in OIS::LinuxMouse::capture() () from /home/babis/Downloads/ror-dependencies/Dependencies_Linux/lib/libOIS.so
#6  0x00005555559bbce9 in InputEngine::Capture (this=0x555557545010)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/utils/InputEngine.cpp:2138
#7  0x0000555555660793 in SimController::UpdateSimulation (this=0x7fffffffe400, dt=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:1741
#8  0x0000555555661c2b in SimController::EnterGameplayLoop (this=this@entry=0x7fffffffe400)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2271
#9  0x0000555555603431 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:354
```
