### ISSUE TITLE
Plane spawning crash

### ISSUE THREAD

**Issue by CuriousMike56** [RigsOfRods/rigs-of-rods#2591]
Added to the FAQ recently, still valid on the latest build: https://docs.rigsofrods.org/gameplay/general-faq/#airplane-spawning-crash

- Set the "Lights" setting (Graphics tab) to `None (fastest)`. 
- Try spawning any aircraft (e.g. An-12), the game will crash.

Any other setting, including `No light sources` (which I assume is the same as none?) doesn't cause the crash.

**Comment by tritonas00** [comment]
If `None (fastest)` is the same with `No light sources` i guess we just can remove the first

**Comment by tritonas00** [comment]
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
0x00007ffff767121a in Ogre::Material::getTechnique (this=0x555559890bf0, index=index@entry=0) at /usr/include/c++/10.1.0/bits/stl_vector.h:1061
1061	/usr/include/c++/10.1.0/bits/stl_vector.h: No such file or directory.
(gdb) bt
#0  0x00007ffff767121a in Ogre::Material::getTechnique (this=0x555559890bf0, index=index@entry=0) at /usr/include/c++/10.1.0/bits/stl_vector.h:1061
#1  0x000055555565f467 in RoR::GfxActor::RegisterCabMaterial (this=this@entry=0x5555598991e0, mat=..., mat_trans=...)
    at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:1324
#2  0x000055555582bc15 in ActorSpawner::FinalizeGfxSetup (this=this@entry=0x7fffffffd4b0) at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:736
#3  0x0000555555832f66 in ActorSpawner::SpawnActor (this=this@entry=0x7fffffffd4b0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/RigSpawner_ProcessControl.cpp:343
#4  0x00005555557ef9b4 in RoR::ActorManager::SetupActor (this=<optimized out>, actor=0x555559b0eda0, rq=..., def=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/BeamFactory.cpp:120
#5  0x00005555557f0b95 in RoR::ActorManager::CreateActorInstance (this=this@entry=0x7fffffffe338, rq=..., def=
    std::shared_ptr<RigDef::File> (use count 6, weak count 0) = {...}) at /usr/include/c++/10.2.0/bits/basic_string.h:907
#6  0x000055555563b0e1 in SimController::SpawnActorDirectly (this=0x7fffffffe310, rq=...) at /usr/include/c++/10.2.0/bits/basic_string.h:907
#7  0x00005555556496b0 in SimController::UpdateSimulation (this=0x7fffffffe310, dt=0.0166667271) at /usr/include/c++/10.2.0/bits/basic_string.h:907
#8  0x000055555564a9d3 in SimController::EnterGameplayLoop (this=0x7fffffffe310)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gameplay/RoRFrameListener.cpp:2290
#9  0x00005555555ed328 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:373
```

**Comment by CuriousMike56** [comment]
The crash appears to happen when creating the beacon light. Spawning the Scania Wrecker also causes this.

**Comment by tritonas00** [comment]
it seems https://github.com/RigsOfRods/rigs-of-rods/pull/2563 fixes this, no crash there.

**Comment by tritonas00** [comment]
works fine in current master, just needs restart to properly apply the change

i will add a notice
