### ISSUE TITLE
The setting Flexbody_EnableLODs crashes the game on some vehicles

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#2627]
So this setting: `Flexbody_EnableLODs` makes the game crashes when a selection of vehicles is spawned.

After looking a couple of times in the logs, there's no mesh error or anything like that.

Vehicles tested :
`KenworthT600custom-HemiBoy`
`MaxT600`
`ChevyK3500`

Turning this setting to `No` makes the vehicle spawn fine.

**Comment by tritonas00** [comment]
```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
Ogre::MeshLodGenerator::generateAutoconfiguredLodLevels (this=0x0, mesh=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/Components/MeshLodGenerator/src/OgreMeshLodGenerator.cpp:80
80	    generateLodLevels(lodConfig)
```

```
(gdb) bt
#0  Ogre::MeshLodGenerator::generateAutoconfiguredLodLevels (this=0x0, mesh=...)
    at /home/babis/Downloads/ror-dependencies/Source/ogre/Components/MeshLodGenerator/src/OgreMeshLodGenerator.cpp:80
#1  0x0000555555889751 in RoR::FlexFactory::ResolveFlexbodyLOD (this=<optimized out>, meshname=..., newmesh=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexFactory.cpp:432
#2  0x00005555558899eb in RoR::FlexFactory::CreateFlexBody (this=this@entry=0x7fffffffdf18, def=0x55555f0bdbc0, ref_node=ref_node@entry=135, 
    x_node=x_node@entry=134, y_node=y_node@entry=145, rot=..., node_indices=std::vector of length 71, capacity 128 = {...}, 
    resource_group_name="4-T600_custom.truck") at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/flex/FlexFactory.cpp:77
#3  0x0000555555831b22 in RoR::ActorSpawner::ProcessFlexbody (this=this@entry=0x7fffffffde90, def=
    std::shared_ptr<RigDef::Flexbody> (use count 2, weak count 0) = {...}) at /usr/include/c++/10.2.0/bits/shared_ptr_base.h:1324
#4  0x0000555555852dae in RoR::ActorSpawner::SpawnActor (this=this@entry=0x7fffffffde90)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/ActorSpawnerFlow.cpp:326
#5  0x0000555555819124 in RoR::ActorManager::SetupActor (this=<optimized out>, actor=0x55555f1dafd0, rq=..., def=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/ActorManager.cpp:103
#6  0x000055555581a378 in RoR::ActorManager::CreateActorInstance (this=this@entry=0x555555baa080 <RoR::App::g_game_context+64>, rq=..., 
    def=std::shared_ptr<RigDef::File> (use count 6, weak count 0) = {...})
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/physics/ActorManager.cpp:346
#7  0x0000555555625127 in RoR::GameContext::SpawnActor (this=0x555555baa040 <RoR::App::g_game_context>, rq=...)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/GameContext.cpp:193
#8  0x00005555555ed255 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:530
```

**Comment by only-a-ptr** [comment]
I'll remove the flexbody LOD altogether.

First off, I'm pretty sure it's an unfinished feature which never worked. RoR creates lower-poly meshes but doesn't configure them as LOD levels. Even if somehow the lower-poly meshes displayed, they wouldn't deform.

Second, sooner or later I'll remake flexbodies to deform using vertex shaders (instead of software deformation). It's the only right way to do it, really, I already experimented and created working test shaders with static deformation.

**Comment by tritonas00** [comment]
https://github.com/RigsOfRods/rigs-of-rods/pull/2630/commits/2a10a6e0b7684dffe1442ea9d9c7bb683e3d7b9f
