### ISSUE TITLE
(1072) Game crash when trying to use the vehicle selection screen 

### ISSUE THREAD

**Issue by WillyB1337** [RigsOfRods/rigs-of-rods#2632]
Basically, whenever I try to open the vehicle selection menu thru the default mapping CTRL+G or thru the topbar GUI, the game instantly crashes.
![Instant crash](https://user-images.githubusercontent.com/16364065/101842632-76992780-3b16-11eb-8757-3733d258b15c.gif)
I saw no specific errors in at the end of the log file. Sounds like an unhandled exception.
[RoR.log](https://github.com/RigsOfRods/rigs-of-rods/files/5676242/RoR.log)
**Even the RigSpawner is affected by this.**

**Comment by WillyB1337** [comment]
I did some investigations and it turns out that a special character like ² is the suspect.

**Comment by tritonas00** [comment]
```
RoR::ImTextFeeder::AddMultiline (this=this@entry=0x7fffffffe280, color=4293256677, wrap_width=wrap_width@entry=-1, 
    text_begin=text_begin@entry=0x55555eee6c00 "\"", '²' <repeats 13 times>, "Desperado\" Rock Buggy²²²²²²²²²", 
    text_end=text_end@entry=0x55555eee6c42 "") at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIUtils.cpp:75
75	        unsigned int c = (unsigned int)*text_pos
```

```#0  RoR::ImTextFeeder::AddMultiline (this=this@entry=0x7fffffffe280, color=4293256677, wrap_width=wrap_width@entry=-1, 
    text_begin=text_begin@entry=0x55555eee6c00 "\"", '²' <repeats 13 times>, "Desperado\" Rock Buggy²²²²²²²²²", 
    text_end=text_end@entry=0x55555eee6c42 "") at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIUtils.cpp:75
#1  0x00005555557176c1 in RoR::DrawColorMarkedText (drawlist=drawlist@entry=0x5555564389b0, text_cursor=..., default_color=..., 
    override_alpha=override_alpha@entry=1, wrap_width=wrap_width@entry=-1, 
    line="\"", '²' <repeats 13 times>, "Desperado\" Rock Buggy²²²²²²²²²")
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIUtils.cpp:238
#2  0x00005555557d263d in RoR::GUI::MainSelector::Draw (this=0x5555575fb5c0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/panels/GUI_MainSelector.cpp:176
#3  0x00005555557112cc in RoR::GUIManager::DrawCommonGui (this=this@entry=0x5555567e18f0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIManager.cpp:486
#4  0x0000555555711302 in RoR::GUIManager::DrawSimGuiBuffered (this=0x5555567e18f0, player_gfx_actor=0x0)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gui/GUIManager.cpp:243
#5  0x000055555566afe1 in RoR::GfxScene::UpdateScene (this=0x555555bad8c0 <RoR::App::g_gfx_scene>, dt_sec=dt_sec@entry=0.0166667141)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/gfx/GfxScene.cpp:241
#6  0x00005555555eb5ef in main (argc=<optimized out>, argv=<optimized out>)
    at /home/babis/Downloads/ror-dependencies/rigs-of-rods/source/main/main.cpp:765
````

**Comment by only-a-ptr** [comment]
@WillyB1337  Good spot, thanks!

Turned out to be one-line mishap, fixed in upcoming PR.
![image](https://user-images.githubusercontent.com/491088/102014399-0973d500-3d56-11eb-83a4-92f523cbbaf6.png)

**Comment by WillyB1337** [comment]
The issue of specials characters is also happening with the chat system. Whenever I try to send a message containing a letter with accents, instant crash.
