### ISSUE TITLE
Crash on updating cache

### ISSUE THREAD

**Issue by Bob-Z** [RigsOfRods/rigs-of-rods#317]
When adding some zip archive to my packs folder, I get a crash like this :

```
 * Input map successfully loaded: 260 entries
Loading category titles from /home/bobz/.rigsofrods/config/categories.cfg
unable to load config file: mods.cache
cache invalid, updating ...
Widget property 'MoveToClick' not found [LoadingWindow.layout]
Texture: rorlogo.png: Loading 1 faces(PF_A8R8G8B8,106x86x1) Internal format is PF_A8R8G8B8,106x86x1.
Adding archive /home/bobz/.rigsofrods/packs/ladder_by_adeodat_and_fonzie.zip (hash: ACA447E12DBD0E8DBEE5CA04170D292157765C4A) (No Compression)
Loading /home/bobz/.rigsofrods/packs/ladder_by_adeodat_and_fonzie.zip
Creating resource group General-1
Added resource location '/home/bobz/.rigsofrods/packs/ladder_by_adeodat_and_fonzie.zip' of type 'Zip' to resource group 'General-1'
Initialising resource group General-1
Parsing scripts for resource group General-1
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-basket.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-basket.material(7): token "3.93700787401575," is not recognized
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-hydro.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-hydro.material(7): token "3.93700787401575," is not recognized
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-hydro2.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-hydro2.material(7): token "3.93700787401575," is not recognized
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-leg.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-leg.material(7): token "3.93700787401575," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-leg.material(23): token "3.93700787401575," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-leg.material(38): token "3.93700787401575," is not recognized
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-renaultkerax.material
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material(7): token "3.93700787401575," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material(22): token "3.93700787401575," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material(37): token "3.93700787401575," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material(52): token "27.5590551181102," is not recognized
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-rotator.material(67): token "7.99212598425197," is not recognized
Parsing script afe677a27542bf4c049fe00a24d001f36074f6da-support.material
Compiler error: unknown error in afe677a27542bf4c049fe00a24d001f36074f6da-support.material(7): token "3.93700787401575," is not recognized
Finished parsing scripts for resource group General-1
Creating resources for group General-1
All done
Preparing to add afe677a27542bf4c049fe00a24d001f36074f6da-Renault_kerax_Ladder.truck
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
Aborted (core dumped)
```

Built on commit : bd62bc8f614451c277476353ff92ffb0e9b4a195
System: Linux ubuntu 15.04 64 bits
Some archive that trigger the issue:
http://dl.free.fr/muALsdKXZ
http://dl.free.fr/mcEJc040n
http://dl.free.fr/nEiwkZglP

back trace:

```
#0  0x00007fdbb330c267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fdbb330deca in __GI_abort () at abort.c:89
#2  0x00007fdbb3c2006d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fdbb3c1dee6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fdbb3c1df31 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fdbb3c1e149 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fdbb3c77d36 in std::__throw_length_error(char const*) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fdbb3c82712 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fdbb6355125 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) ()
   from /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.55.0
#9  0x00007fdbb3c841fc in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007fdbb5f48714 in Ogre::StringConverter::parseInt(std::string const&, int) ()
   from /usr/local/lib/libOgreMain.so.1.8.2
#11 0x0000000000c7ba85 in RigDef::Parser::_ParseNodeRef(std::string const&) ()
#12 0x0000000000c6aa13 in RigDef::Parser::ParseSubmeshUnsafe(std::string const&) ()
#13 0x0000000000c6b000 in RigDef::Parser::ParseSubmesh(std::string const&) ()
#14 0x0000000000c60eb1 in RigDef::Parser::ParseLine(std::string const&) ()
#15 0x0000000000dc0e08 in CacheSystem::fillTruckDetailInfo(CacheEntry&, Ogre::SharedPtr<Ogre::DataStream>, std::string) ()
#16 0x0000000000dc0402 in CacheSystem::addFile(std::string, std::string, std::string, std::string) ()
#17 0x0000000000dc0054 in CacheSystem::addFile(Ogre::FileInfo, std::string) ()
#18 0x0000000000dc3eac in CacheSystem::parseFilesOneRG(std::string, std::string) ()
#19 0x0000000000dc3976 in CacheSystem::parseKnownFilesOneRG(std::string) ()
#20 0x0000000000dc76bc in CacheSystem::loadSingleZip(std::string, int, bool, bool) ()
#21 0x0000000000dc68d0 in CacheSystem::loadSingleZip(Ogre::FileInfo, bool, bool) ()
#22 0x0000000000dc82cd in CacheSystem::loadAllZipsInResourceGroup(std::string) ()
#23 0x0000000000dc8abb in CacheSystem::loadAllZips() ()
#24 0x0000000000dbba4a in CacheSystem::generateCache(bool) ()
#25 0x0000000000db57f2 in CacheSystem::Startup(bool) ()
#26 0x0000000000dd252f in RoR::MainThread::Go() ()
#27 0x0000000000dcfc49 in main ()
```

**Comment by Max98** [comment]
@only-a-ptr It looks like it has something to do with the parser.

**Comment by only-a-ptr** [comment]
http://dl.free.fr/getfile.pl?file=/uALsdKXZ - Tested with incremental cache update, worked OK

**Comment by only-a-ptr** [comment]
@Bob-Z Thanks for the detailed crash report, but unfortunately I wasn't able to reproduce this.
Please re-compile with latest code and test again.

**Comment by Bob-Z** [comment]
I have just tried with rev a77a71553258204d2522cab7c5ba15bf976cfb75 and all is back working OK too.
Consider it fixed.
