### ISSUE TITLE
Segmentation fault in DashBoardManager::windowResized

### ISSUE THREAD

**Issue by ulteq** [RigsOfRods/rigs-of-rods#905]
Steps to reproduce:
* Connect two clients (A and B) to a server
* Spawn a truck on client A
* Spawn a truck on client B
* Delete the truck on client A
* Move the mouse back into client B

```
Thread 1 "RoR" received signal SIGSEGV, Segmentation fault.
DashBoardManager::windowResized (this=0x0) at /home/archie/rigs-of-rods/source/main/gui/DashBoardManager.cpp:212
212		for (int i=0; i < free_dashboard; i++)
(gdb) bt
#0  DashBoardManager::windowResized (this=0x0) at /home/archie/rigs-of-rods/source/main/gui/DashBoardManager.cpp:212
#1  0x00000000007786e9 in BeamFactory::windowResized (this=0x2ec6370) at /home/archie/rigs-of-rods/source/main/physics/BeamFactory.cpp:998
#2  0x0000000000687986 in RoR::GUIManager::windowResized (this=0x23ff1c0, rw=0x7ffff7e731d8) at /home/archie/rigs-of-rods/source/main/gui/GUIManager.cpp:209
#3  0x00007ffff7a7ab1d in ?? () from /usr/lib/libOgreMain.so.1.9.0
#4  0x00007ffff7a7af6c in Ogre::WindowEventUtilities::messagePump() () from /usr/lib/libOgreMain.so.1.9.0
#5  0x00000000005607e5 in RoR::MainThread::EnterGameplayLoop (this=this@entry=0x7fffffffe420) at /home/archie/rigs-of-rods/source/main/MainThread.cpp:850
#6  0x00000000005668b8 in RoR::MainThread::Go (this=this@entry=0x7fffffffe420) at /home/archie/rigs-of-rods/source/main/MainThread.cpp:458
#7  0x000000000053d91a in main (argc=<optimized out>, argv=<optimized out>) at /home/archie/rigs-of-rods/source/main/main.cpp:239
```

**Comment by only-a-ptr** [comment]
If I understand it correctly, the problem is client B trying to update dashboard on networked truck A which was deleted in the meantime. This feels like a bug in truck-removal code: the dashboard should have been removed along with client-A-truck.
